### ISSUE TITLE
word count doesn't count?

### ISSUE THREAD

**Issue by incantatem1** [yefengr/obsidian-daily-statistics#1]
it just says "0" everywhere which is obviously wrong

standard settings

newest version of obsidian

still the same after restarting

**Comment by yefengr** [comment]
This plugin can only count the words typed after installation; it cannot count the words typed before. If you have just installed the plugin, it is normal for the count to be 0.

**Comment by incantatem1** [comment]
ok, actually i thought so too, but then it didn't count the words i typed after installation either?

**Comment by incantatem1** [comment]
oh, nevermind, it does now after deactivating and reactivating
