### ISSUE TITLE
discovered another issue

### ISSUE THREAD

**Issue by incantatem1** [yefengr/obsidian-daily-statistics#2]
the count is entirely wrong, it counts not words, but like every 2-3 letters and also spaces? is that because it's adapted to chinese (i think it's chinese, sorry if i'm wrong)?

**Comment by yefengr** [comment]
I apologize, what is currently being counted is indeed only the number of characters, not the number of words.

**Comment by incantatem1** [comment]
ok, got it! is that intentional and i misunderstood it, or will you fix it to count words, or maybe add an option for both?

**Comment by yefengr** [comment]
If there is time later, I will add an option to set whether to count characters or words.

**Comment by Damaskox** [comment]
I would also love to see the WORDS implemented 💗

**Comment by yefengr** [comment]
Added word count functionality, you can give it a try.
@incantatem1  @Damaskox

**Comment by incantatem1** [comment]
doesn't seem to work :(

**Comment by yefengr** [comment]
Thank you for the feedback. The issue has been fixed; you can try again.
@incantatem1

**Comment by Damaskox** [comment]
@yefengr It seems to work (I had one minute time to try - testing later more)!

Thanks a many!

**Comment by Damaskox** [comment]
I just noticed that it hasn't counted words for four days 👀
